### ISSUE TITLE
Fix action set offsets

### ISSUE THREAD

**Issue by totycro** [unknown-horizons/unknown-horizons#1379]
The player ship and others are misplaced by a few pixels, one can see it when a ship is near the coast and the view is rotated. This can probably be fixed by correcting the offset in `units/__init__.py:65`.

Also check buildings, it looks a bit odd when the surrounding is highlighted (the buildings aren't exactly above the non-highlighted tiles below it.

![bug-1370](https://cloud.githubusercontent.com/assets/50333/19413544/86501c2a-9330-11e6-916f-54f7c8bd3237.png)
- [ ] Fix offsets for every rotation in ships
- [x] Check which buildings seem to hover above ground when activating tile highlights
- [x] Fix building offsets

**Comment by LinuxDonald** [comment]
@stubb what about this issue?

**Comment by LinuxDonald** [comment]
@stubb in what file must the offset corrected?

**Comment by squiddy** [comment]
Updated the issue with a screenshot. @LinuxDonald If I had to guess, it's this line https://github.com/unknown-horizons/unknown-horizons/blob/8049731/horizons/world/units/__init__.py#L92

The `:shift:center+0,bottom+8` part. We could adjust that for every angle until it works in all rotations.

**Comment by LinuxDonald** [comment]
Must I change only the numbers in that line?

**Comment by MasterofJOKers** [comment]
Well yes and no. We need to change the numbers in that line based on the rotation. My guess would be, that it's always 8, but sometimes center+8, then center-8 and bottom-8 ... but that's just a guess. If you only change the numbers in that line, it should only look correct in one rotation, I guess.

**Comment by squiddy** [comment]
Buildings have an issue as well:

![uh-bug-1379](https://cloud.githubusercontent.com/assets/50333/19416094/c099d022-9387-11e6-875b-c6cd0e9ed675.png)

On the right it almost looks like the building is hovering above ground. When activating the grid, it seems like grid and building are aligned correctly, but don't seem to match the tiles, they should be moved down a bit.

**Comment by squiddy** [comment]
> yeah, part of that ticket is investigating how the image size (and proportions) play into this fife stuff i guess

> like, if i use a 256x256 image, or a 192x192 image, or a 128x128 image all for the same "2x2" building, what does change

-- eoc on irc

**Comment by LinuxDonald** [comment]
Charcoal Burning is broken too. 
![2016-10-16 12-16-52 759167](https://cloud.githubusercontent.com/assets/1757651/19417032/fee121f4-93a1-11e6-9f6f-513b56c36fa8.png)
![2016-10-16 12-19-09 570352](https://cloud.githubusercontent.com/assets/1757651/19417033/fee1d504-93a1-11e6-93ac-b1f48d007453.png)

**Comment by MasterofJOKers** [comment]
For the ship, changing the line @squiddy mentioned to +48 instead of +8 fixes the offset. I don't know what other units might be affected by that change, though. That's need investigation, as it might move other units to a wrong location.

**Comment by AndyMender** [comment]
It's theoretically possible to fix the offsets on the level of individual .png animation frames. This then would remove the need for the offset mechanics in UH entirely. Like so:
https://imgur.com/a/74tXF
However, since we have different dimensions for different unit/building objects, it's rather tricky.

Another thing is that the .png object images are loaded correctly (aligned with the grid), but the underlying map placeholder (differently colored grass tile) is not, yet it actually defines where the game *sees* the object. Instead of shifting the images, we would probably need to address the tiling code.

@LinuxDonald thoughts? :)

**Comment by AndyMender** [comment]
@LinuxDonald  @MasterofJOKers @ChrisOelmueller and other long-time members/players, please do have a look at the building offsets in long-running games. If there are problems still, I'll try to find a better solution.

**Comment by LinuxDonald** [comment]
Needed changes when offset is fixed: https://github.com/unknown-horizons/unknown-horizons/pull/2644

**Comment by AndyMender** [comment]
I was thinking about this recently and I believe it would be best to have a static set of per-building offsets (as JSON?). I tried adjusting the algorithm we have implemented at the moment and fixing offsets for some buildings breaks them completely for others.

**Comment by squiddy** [comment]
Do we really need per-building offsets? Couldn't this also be an issue with inconsistent graphics where the bottom is misaligned? Offsets per tile configuration (2x2, 2x3, 4x2) perhaps, but for every building? Sounds like a hack.

**Comment by AndyMender** [comment]
I feel like the current offset system is already a hack, because we should be able to load the images onto the grid directly :(.

What do you mean by the bottom being misaligned? As in the render not being always in the centre of the image?

**Comment by squiddy** [comment]
> What do you mean by the bottom being misaligned? As in the render not being always in the centre of the image?

Yes, kinda. Not sure if it really has to be in the centre, but anyway, I'm suggesting that not all the images are aligned consistently.

**Comment by AndyMender** [comment]
So far I have looked at the pirate ship, deer and the woodcutter's hut. I tried resizing and re-arranging a single render of a woodcutter's hut within an image, but even when moving the render to one of the edges, the alignment was imperfect and resizing is out of the question, because then FIFE scales the image up/down. 

Apart from that, the renders are as close to the centre of their respective images as possible. I tried going through the tiling code carefully, but it's difficult to say where the offsets come from. As I mentioned, our current algorithm calculates arbitrary offsets for each angle, using image dimensions as well, but the effects are not good.

The reason why I suggested static offsets was that this would allow us to input the offset values and be done with it. Regardless, I can of course try to develop the algorithm further and maybe group images by size so that the calculated offsets make more sense :).

**Comment by AndyMender** [comment]
I still need to work on the 315 angle for the brickyard.

**Comment by AndyMender** [comment]
The dynamic algorithm (using a quadratic equation) was still imperfect so I had to group buildings into sets 3x3, 2x2, 1x1, etc. and apply static offsets per each angle (45, 135, 225, 315). The brickyard is handled individually (a 2x4 building) and so will the charcoal be (2x3 building). Alas, I couldn't find a better way of handling the offsets so this "hack" was needed.

**Comment by AndyMender** [comment]
@squiddy, could you possibly have a look at this and state whether the proposed solution is at least acceptable? :)

**Comment by squiddy** [comment]
@andymender Pushing changes into master and THEN asking whether things are acceptable is really not the way to go about this. 

I suppose the changes are fine (I don't have time right now to look into this) though. I'll get back to you on this later.

**Comment by AndyMender** [comment]
The buildings look alright now, though I am not sure about the ships. They seem to be able to move to designated positions and they don't *rub* against the coastline anymore. @LinuxDonald what do you think?

**Comment by LinuxDonald** [comment]
Is this bug/problem real fixed or use we here an workaround?

**Comment by AndyMender** [comment]
It's a workaround as much as the original solution.

**Comment by squiddy** [comment]
So what's the status here @AndyMender, is this done?

**Comment by AndyMender** [comment]
@squiddy the offsets were adjusted and look much better now. In my opinion it's ready for shipping :). I think we can close the issue.

**Comment by squiddy** [comment]
Alright, cool. :)

**Comment by jmdejong** [comment]
For me the ships are still very obviously misplaced.

I'm currently working on a general solution for these offsets, without tons of if statements.
I think I'm almost done for the buildings and base tiles.
This solution also solves #661 

About bottom misalignment: for grass tiles the bottom is 4 or 5 pixels higher than for other base tiles.
This seems to be done on purpose in an attempt to simulate elevation.
However, buildings (including trees) don't have this, and will therefore be misaligned with the ground on which they are standing.
Adjusting the alignment for buildings isn't really an option because that would mean that they would be misaligned when built on other base tiles (like beaches)
