### ISSUE TITLE
Add 'sails' to the windmill

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#1626]
Normally windmills like [https://github.com/unknown-horizons/unknown-horizons/blob/master/content/gfx/buildings/citizens/as_windmill0/idle/45/01.png our towermill] have sails¹ attached to the wings, to get a greater surface, which will improve the mills 'speed' -> more rotations of the millstone. I'am not really sure if a mill without sails will work, for me it looks like that the surface in relation to the power which is needed to move the millstone doesn't fit. Maybe we can keep a version without sails for the decommissioned state of the mill and have one with sails for the normal state. Not sure if there could be an animation which handles the time between have no sails and 'wings completely covered by sails'.

For reference:
* [http://upload.wikimedia.org/wikipedia/commons/6/60/Molenaar_De_Helper.JPG ¹]

[> Link to originally reported Trac ticket <] (http://trac.unknown-horizons.org/t/ticket/1626)

**Comment by janexx** [comment]
The windmill looks a bit different because the original windmill was not used within the uh default Blender scene. I imported it in a new default Blendder file. And I also rendered it 128x128 instead of 128x256. When you @stubb @LinuxDonald are happy with that, the issue can be closed with commit 2538f3b36780a55cd78ed65fdb28cdff8b28fc10 .

**Comment by LinuxDonald** [comment]
Thank you for your work @janexx :) it looks nice :)
