### ISSUE TITLE
Create female gfx

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#1635]
This suggestion is from a command of [http://www.youtube.com/all_comments?v=0lvMuflTuok this youtube video].
Thats the german suggestion:
'''wo waren die Frauen ,? hab keine gesehen...'''
the english translation:
'''where are the woman, i didn't see any...

This ticket covers the task to create female gfx for the different units we have.

[> Link to originally reported Trac ticket <] (http://trac.unknown-horizons.org/t/ticket/1635)

**Comment by martingeiger** [comment]
![female_gfx](https://cloud.githubusercontent.com/assets/16446328/12050244/48e5f9b8-aef2-11e5-85d1-bea0521847e4.png)

**Comment by martingeiger** [comment]
![bildschirmfoto 2015-12-30 um 02 16 17](https://cloud.githubusercontent.com/assets/16446328/12050280/1a901840-aef3-11e5-9189-42f2f9b7206f.png)
{Ingame}

**Comment by martingeiger** [comment]
Hello everyone,
I started yesterday with the female_gfx.
I don't know how detailed the texture should look,
but that's then a first preview. Any suggestions ?
Thanks

**Comment by LinuxDonald** [comment]
i Think it looks okay :) When you are done with the grafic and animation please make an Pull request.

**Comment by janexx** [comment]
It looks very nice, the textures are good, I think there are no more details needed.

**Comment by janexx** [comment]
is finished with commits 9a32771b0b0a5e83ad247f9b70a9ba9a08af5538 and 70290d9c616ef327ca3dcb31840db5c6ea105f20

![0](https://cloud.githubusercontent.com/assets/6216898/12080741/1f8d4e88-b265-11e5-96d1-62a184e7b395.png)

Good work Martin!

**Comment by stubb** [comment]
@martingeiger great work!

**Comment by martingeiger** [comment]
thanks a lot

**Comment by martingeiger** [comment]
![male_gfx](https://cloud.githubusercontent.com/assets/16446328/12101228/d7a76f98-b333-11e5-953a-552b523b6053.png)

I made now a male-gfx as well.
The figures are for the tent-buildings ?
Different houses, different dresses ?

**Comment by martingeiger** [comment]
And it renders now fine

**Comment by LinuxDonald** [comment]
you can make diffrent dresses when you like at the moment we have 4 steps:
Sailors
Pioneers
Settlers
Citizens

but than we need for woman to more dresses

**Comment by martingeiger** [comment]
sure, like the different society classes. 
From poor to noble etc.

**Comment by LinuxDonald** [comment]
yes :)

**Comment by martingeiger** [comment]
OK. let's do this.

**Comment by martingeiger** [comment]
![bildschirmfoto 2016-01-09 um 10 28 35](https://cloud.githubusercontent.com/assets/16446328/12215416/3164f01a-b6bc-11e5-9aee-4961c99eff26.png)
![bildschirmfoto 2016-01-09 um 10 25 47](https://cloud.githubusercontent.com/assets/16446328/12215417/317b405e-b6bc-11e5-8fe9-8e709bd79ee9.png)
![bildschirmfoto 2016-01-09 um 10 27 26](https://cloud.githubusercontent.com/assets/16446328/12215418/31900a52-b6bc-11e5-975e-1dbfae1d1c95.png)
![bildschirmfoto 2016-01-09 um 10 26 58](https://cloud.githubusercontent.com/assets/16446328/12215419/31a8913a-b6bc-11e5-93e7-255f122baf0a.png)

Good Morning, I made a little preview for the pioneer and settler costumes, had not so much time the last days. Any suggestions ?

**Comment by martingeiger** [comment]
The citizens will follow tomorrow.

**Comment by stubb** [comment]
@martingeiger Great work :+1: 
I don't have a suggestion, but a small question. Is it intended that the woman are pale in comparison to the men? We should check if it's difficult do differentiate the hands from the tops in the resulting ingame-renderings.

**Comment by martingeiger** [comment]
Yes that's right it just stays the same teint.

Let me try something like the inhabitants
getting paler how richer they become.

In a historical aspect we can say "aristocratic pallor".

**Comment by LinuxDonald** [comment]
We have that steps of inhabitants:

Sailors
Pioneers
Settlers
Citizens
Merchants (not ingame yet)
Aristocrats (not ingame yet)

**Comment by janexx** [comment]
@martingeiger  
Thanks at first for your good work and your last 2 commits. But there went some things wrong (don't worry).

1) We store the source files (blender file, textures and ideally a licence text) in the gfx repository: https://github.com/unknown-horizons/gfx
You can compare your folder structure with folders from other graphic artists under the link above. It would be not bad, when you could sort your files like there.
The graphics which appear in the game itself are stored here: https://github.com/unknown-horizons/unknown-horizons/tree/master/content/gfx
Your mens and womens would come in the "units" folder there. So please move your animation sets to this place.

2) Before you move your animations, please check them again. I found some errors like:
* In the gfx repo in martingeiger/female_gfx/pioneer/final there are empty graphics in the "idle" folder and the move folder  is missing
* In your folder /female_gfx/sailor/final/idle is the background of the images grey instead of transparent. But you can delete the whole female sailor folder because I uploaded it already: https://github.com/unknown-horizons/unknown-horizons/tree/master/content/gfx/units/inhabitant/sailor/as_female
* In the folder pioneer/data/final/idle are the woman very white. Maybe it rendered without textures?
* In your folder /female_gfx/settler/data/final/idle/ there are empty images.
* In your folder male_gfx/sailor/final/ are in "idle" again empty images.
* In male_gfx/sailor/final/move rotated the camera in 90 instead of 45 degree, so that the mens are rendered only from 4 directions instead of 8. Just take the script "render_unit.py". There I set set up all rigth for this. And also notice that the mens and womens have to look to the right side. You can always take the pics in the following place as reference: https://github.com/unknown-horizons/unknown-horizons/tree/master/content/gfx/units/inhabitant/sailor
* Was I wrote in the prevous point is also at the male pioneers and the male settlers move animation. And the idle graphics are missing. For this you can simply copy the first animation graphic. Just look how the existing idle folders are structured.

That was quite much. But don't worry. If you have questions or problems, feel free to ask. Anyway nice work. ;)

**Comment by martingeiger** [comment]
Thank you for the points,
I change it quickly.

**Comment by janexx** [comment]
@martingeiger: Do you want to put the rendered graphics in the directory metioned above to see the inhabitants in game? They are not yet in. I think some of them must be rendered again. Or if you want I can do that too.
