### ISSUE TITLE
Make the mouse sensitivity setting scale make sense

### ISSUE THREAD

**Issue by otinn** [unknown-horizons/unknown-horizons#1971]
The current mouse sensitivity setting scale is from -10% to 50% with the default at 0%.
We should use a scale that makes more sense, such as 0.5x, 1x (default), and 2x (these limits are just an arbitrary example).

**Comment by LinuxDonald** [comment]
@CrafterSvK do you want maybe work on this?

**Comment by CrafterSvK** [comment]
Yeah sure I will take a look

**Comment by LinuxDonald** [comment]
For translation we have an script do only code changes :-)

**Comment by CrafterSvK** [comment]
#2473

**Comment by AndyMender** [comment]
![mouse_sensitivity](https://cloud.githubusercontent.com/assets/15969405/26764344/830f4950-4965-11e7-9fae-382cd4df37b7.png)
As @squiddy mentioned here: https://github.com/unknown-horizons/unknown-horizons/pull/2473 , mouse sensitivity can have a raw value of -0.99 to 10. This is interpreted directly by FIFE. However, upon testing it is very clear that values lower than -0.4 don't really make sense, because then the cursor starts to *glue* to a specific position after each mouse hover. Values higher than 0.5 cause the cursor to glide rapidly across the screen, making such settings equally useless. Therefore, I selected a "sane default" range of -0.2-0.5. This is later formatted in the menu to represent a factor of the base mouse sensitivity (value 0.0). For details, see the attached screenshot.

@LinuxDonald @squiddy thoughts?

**Comment by AndyMender** [comment]
@squiddy, can this be closed as completed or should I adjust the mouse sensitivity setting range? The related commits were already merged into master.

**Comment by squiddy** [comment]
I'd say you can close it. There was the suggestion about using a StepSlider with discrete values, but not sure if we want to go down that path.
