### ISSUE TITLE
Settlement production overview overflow

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#2169]
With large settlements, the space provided there is not enough.
Should either be scrollable, or find a better way of representing the information.

![show me](https://f.cloud.github.com/assets/373440/1311664/611a90a4-3215-11e3-9e81-765fb095e434.png)

**Comment by LinuxDonald** [comment]
An Scrollbar would be nice here and should be easy to add it. It should like as in the Credits menu for example.

**Comment by squiddy** [comment]
I dislike the combination of showing a book-like interface and using a scrollbar. Especially since in this case, we would be wasting the space on the right.

I think each page (we've got two) offers space for 21 resource items, so 42 in total. Which might be still not enough. Adding scrollbars to each page is confusing in my opinion. I like the interface of the logbook where you actually scroll pages.

**Comment by LinuxDonald** [comment]
That is an nice idea too. Or adding book tabs for different resource groups.

**Comment by LinuxDonald** [comment]
![2016-10-25 17-51-17 443717](https://cloud.githubusercontent.com/assets/1757651/19693423/c7bee65c-9adb-11e6-8d7b-a730ea702460.png)
![2016-10-25 17-51-14 041771](https://cloud.githubusercontent.com/assets/1757651/19693424/c7c08408-9adb-11e6-8d86-62c8bc938733.png)
