### ISSUE TITLE
Route menu is messy

### ISSUE THREAD

**Issue by acini** [unknown-horizons/unknown-horizons#2219]
![snapshot6](https://f.cloud.github.com/assets/6072881/1673224/9a9fba68-5ce3-11e3-86fe-64f6804ad691.png)
![snapshot12](https://f.cloud.github.com/assets/6072881/1673238/f2c56314-5ce3-11e3-8c64-cae831a53dac.png)
The route menu is not ergonomic.
1. The load/unload toggle button is confusing. It switches between 3 different states: 2 toggle states and 1 hover state. It could simply be 2 toggle states.
2. The red arrow can be placed before the ship icon and pointing away from it. This way, it will be give a solid feel making as ship icon stays in place.
3. The "scrollbar" which adjusts item load-unload amount should have easily clickable arrows on top and bottom ends. Maybe pressing shift with will could load 5x amount, with ctrl 10x etc.
4. Currently only the area taken by "X" or "Item" is clickable. The "18t" area and area on right side of resource picture can be made clickable so that player doesn't have to point to tiny pixel area everytime.
5. Large player names (here, Unnamed Traveler) overlaps load/unload slots. Maybe they could be made "Unnamed Tra..." etc. or reduce font size. Or maybe one could implement player's name character limit.
##

**Comment by CrafterSvK** [comment]
Easiest thing is remove the hover thing. It is confusing and I had to learn how it works. That would be much easier :)

**Comment by jorgesumle** [comment]
@CrafterSvK I like that feature :(

**Comment by janexx** [comment]
I always don't know, wheter the hover message tells me the state how is it now or how it should be, when I click on an arrow. I am always confused with this menu.

**Comment by LinuxDonald** [comment]
I think the gui needs that hover get removed and a little redesign.

**Comment by CrafterSvK** [comment]
It is okay I guess but it is confusing. If you remove it. It iwll be much better

**Comment by CrafterSvK** [comment]
#2467

**Comment by LinuxDonald** [comment]
@CrafterSvK you could fix the other points from the issue too?

3. The "scrollbar" which adjusts item load-unload amount should have easily clickable arrows on top and bottom ends. Maybe pressing shift with will could load 5x amount, with ctrl 10x etc.
4. Currently only the area taken by "X" or "Item" is clickable. The "18t" area and area on right side of resource picture can be made clickable so that player doesn't have to point to tiny pixel area everytime.
5. Large player names (here, Unnamed Traveler) overlaps load/unload slots. Maybe they could be made "Unnamed Tra..." etc. or reduce font size. Or maybe one could implement player's name character limit.

**Comment by jorgesumle** [comment]
Here is a similar problem to #2474.
![captura de pantalla de 2016-09-06 01 39 10](https://cloud.githubusercontent.com/assets/14212780/18258290/06214582-73d3-11e6-88a4-0b2160ca51da.png)

**Comment by LinuxDonald** [comment]
@jorgesumle i cant reprdouce your text out of gui error.

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/issues/1688

**Comment by LinuxDonald** [comment]
i will take an look at this branch how it looks on it and what is done there: https://github.com/unknown-horizons/unknown-horizons/pull/2307

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/pull/2523

**Comment by LinuxDonald** [comment]
I like the gui from #2523 but i dont how to fix and it need changes too. As you can see here we have an Text problem on the gui: https://cloud.githubusercontent.com/assets/1757651/19618863/9b0ab366-9856-11e6-800e-3a3f6d9bfd31.png

I think the Name of the Island and the player name shoud be above the Trade slots?

**Comment by squiddy** [comment]
> I think the Name of the Island and the player name shoud be above the Trade slots?

I agree.

> I like the gui from #2523 [...]

Not sure I like the button with the red arrow on the right. Is that intuitive? Why is it near the controls, that either remove a waypoint or move it?

**Comment by LinuxDonald** [comment]
I think as tooltip say it unload the compelte inventory but i dont know exactly because double click on it crashes uh. Crash log is in the pr.

**Comment by janexx** [comment]
Hey all, here an edited screenshot how it could look like / a propsal how it could be implemented:
![poposal_route_menu_janexx](https://cloud.githubusercontent.com/assets/6216898/20436223/a39c6b14-adaf-11e6-9989-43bb04c5b679.png)

Instead of the red arrow for unloading everything on board I find a symbol with a red arrow more intuitiv. I have created the button by myself, it doesn't exists yet.
I also made the Name of the Island above the trade slots.

**Comment by LinuxDonald** [comment]
Looks good

**Comment by AndyMender** [comment]
The routeconfig menu went through many changes, rearrangements, etc. One could probably polish it _ad infinitum_. Are further adjustments needed for this issue or may I close?

@LinuxDonald @squiddy @janexx thoughts? :)

**Comment by squiddy** [comment]
How does it look right now? Can you provide screenshots?

**Comment by AndyMender** [comment]
Like so:
![routeconfig_fixed](https://cloud.githubusercontent.com/assets/15969405/25454496/e78e52c0-2acc-11e7-98eb-e88344819191.png)

**Comment by LinuxDonald** [comment]
I will look today afternoon if I can place the player and city name over the trade slots. As in the Screenshot from janexx.

**Comment by AndyMender** [comment]
The icon with the trash bin to the right is handled by a different piece of Python code / xml template so that would need to be repositioned as well.

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/commit/30ea211b40c8d221f7be5912e60ccc5b9f790369

More gui fixes.

**Comment by AndyMender** [comment]
Adjusted maximum `player_name` length in routeconfig.py, since now `warehouse_name` and `player_name` are above trade_slots: https://github.com/unknown-horizons/unknown-horizons/commit/a81dd466fbe67528d693f1def2845b90f9c7d680

**Comment by AndyMender** [comment]
![routeconfig_fix2](https://cloud.githubusercontent.com/assets/15969405/25558329/79bc4e46-2d24-11e7-8c69-7d2b62435eed.png)
And I would leave it at that. Adding a ScrollArea would require redefining some of the ScrollArea widget attributes, since it behaves a bit differently than a regular VBox so we're limited to 5 trade slots.

**Comment by AndyMender** [comment]
@LinuxDonald, I think this is completed, right? :)

**Comment by LinuxDonald** [comment]
Yeah I think it can be closed. The gui will maybe need later more work. Based on player feedback.
