### ISSUE TITLE
Squash translation commits

### ISSUE THREAD

**Issue by iqualfragile** [unknown-horizons/unknown-horizons#2280]

**Comment by squiddy** [comment]
If I understand the integration correctly, translations on weblate are automatically pushed into the repository.

How about doing this manually? Have people translate stuff on weblate, and once a while, pull the changes manually and commit. Updating source files on weblate (if that is even necessary) could be done as part of CI.

This seems to be related to that idea: 
https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts

**Comment by squiddy** [comment]
I wasn't aware that I resurrected a 2 year old ticket. It isn't that big an issue, is it? I don't think this is relevant for the 2016.2 milestone.

**Comment by iqualfragile** [comment]
please reopen, this is not resolved yet.

**Comment by squiddy** [comment]
I'd be happy to, but first we need to clarify some things, your original post didn't contain many information.

What's the problem here? Right now, you're merely proposing a solution.
Why is this important? Nothing happened in two years.
Whom does it affect? Our players, developers?

**Comment by iqualfragile** [comment]
i think its quite clear to everybody that the problem is that 90% of the commits in this repository are microscopic ones generated by some web-translation-service, spamming the git logs. this is a probem to everybody trying to follow the development of unknown horizons.
you don't just close an issue because no one is working on it, thats not how bugtrackers work.

**Comment by squiddy** [comment]
I don't appreciate your condescending tone. As far as I know you're the first one to raise this issue here, so I don't think you're in the position to speak for *everybody*.

Our resources are limited, as is in most communities. We always appreciate contributions from existing / new members of this project. Feel free to investigate this, I linked something possible relevant in https://github.com/unknown-horizons/unknown-horizons/issues/2280#issuecomment-252481387. If you have questions, I'm happy to help.

I do get your point, however this problem isn't magically going to solve itself by staying open another 2 years. Bugs get fixed by people, not by opening issues alone.

**Comment by squiddy** [comment]
I will reopen it, but remove the milestone. Let's see how that goes.

**Comment by MasterofJOKers** [comment]
By squashing commits (and if I understand you correctly, you mean all weblate commits, i.e. for all languages and authors over a given time period) we are losing the ability to attribute changes to an author. Basically, we would have to include the diff per author in the commit message, to still keep that information. I don't like that.

I would prefer splitting the translations off into another repo (and maybe use it as a submodule), so that one can follow unknown-horizons without getting spamed with translation-commits.

**Comment by ChrisOelmueller** [comment]
We did use to have a separate repository, but that simply didn't play well with how we wanted to integrate in-game changes to text (and left quite something to be desired on the maintenance front too, due to submodules' inherent added complexity).

If the problem that's to be fixed here is indeed a lack of development progress information, instead of making certain processes worse for little to no gain (like squashing commits), how about we try and update our changelog a bit more frequently? That would help more folks, and even the ones that don't have the patience of following "git logs" frequently.

@iqualfragile 
You can exclude certain authors from your git log. That's something you do once. It's something you can do on your own. It's something that doesn't require us to do anything. Which is good because we have limited resources at our disposal. To save you the time of even looking things up: gibson042/git-log-except 

Everybody else:
Let's please re-evaluate what we want to do about the perceived problem (and possibly answer the question in a new ticket) at some later point in time. For now I, personally, couldn't care less and definitely don't think it's urgent in any way, let alone requires everybody to chime in or think of possible solutions.

**Comment by iqualfragile** [comment]
@squiddy sorry, i was a bit out of sleep
