### ISSUE TITLE
Crash by clicking diplomacy button twice in a row

### ISSUE THREAD

**Issue by MadMac** [unknown-horizons/unknown-horizons#2315]
I'm getting a crash everytime by clicking diplomacy button under minimap twice.

[Traceback](https://gist.github.com/MadMac/7630b6128e270ba49104)

How to reproduce:
Start any game. Click diplomacy button under minimap twice in a row.

I used FIFE installer to install FIFE because I couldn't build it with the old development kit version. 

Version: 284bd4b
Windows 7 64
Python 2.7.8

**Comment by stubb** [comment]
Thanks for reporting. Seems like that was introduced recently during some mem leak fixing.

**Comment by pinkfloyda** [comment]
OK, I see the crash when more than 1 PlayerDiplomacyTab shown in DiplomacyTab. It seems my previous pull request for mem leak fix is not good ..... (we should never hide a tab if it has not been shown before). Can pull back my previous pull request and for mem leak issue, I come up with 2 solutions:

1) Fix in fifechan side so that creating a widget should not add it into its all_widgets list, only showing widget can add it and hiding widget remove it from the list. (This fix can get rid of some other mem leak issues for UH)
2) Fix in UH side to defer creating widgets for tabs (lazy_loading), only create when showing it as current tab.

**Comment by stubb** [comment]
Since there isn't any upcoming fife release, a fix within the UH code is required.

**Comment by pinkfloyda** [comment]
OK, as for TabInterface, I notice there is a class variable called lazy_loading=false by default. And for some tab classes, this has been set to be true, --> see InventoryTab for an example. Is it possible to set that lazy_loading=true by default ? Is there some performance issue for such change ?

**Comment by helios2000** [comment]
The reason that the Widgets are added to the list on init() is because of xml loading. Without that there is no reference to the freshly loaded Widgets.

So you want to create Widgets in code and use it later?
If so a simple flag could be added to the Widget class that indicates it and prevents the Widget to be added to the manager. So the gc would remove it right after the last reference is gone.

**Comment by pinkfloyda** [comment]
@helios2000 yes, you are correct, the basic idea is to not add widget into list upon init(), do you know which flag can indicate and prevent the widget to be added to the manager? I explored the code find the manager side just add the widget into its list once inited (xml loaded) no matter how. Is it something to do with the lazy_loading concept?

**Comment by helios2000** [comment]
Sorry, I don't know much about UHs gui code. It was just a suggestion from me, how it could be solved within Pychan. I think that lazy_loading is from UH.

The other case where it's added to the manager is on addChild(), so should the proposed flag also prevent this? And we need a name for the flag :)

**Comment by pinkfloyda** [comment]
@helios2000 ok, actually most places of addChild() are not issues for mem leak, because if the root parent widget gets hidden and reference removed, all the children gets hidden and reference removed as well. Most places the root parent widgets come from xml, which are inited() explicitly in UH. And if we can safely hide all those xml-loaded widgets, I think we can get rid of most of the mem leaks.

**Comment by helios2000** [comment]
Ok, sounds good. I think it should be no problem to call hide() for new Widgets. So the flag would be superfluous and it could be fixed on UHs side.
