### ISSUE TITLE
Form down now for half year/fix phpbb forum theme [$15]

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2326]
Bring the Forum back online or is UH dead??
##

**Comment by stubb** [comment]
Since the last update the phpbb theme is broken, it need to be adopted/updated/fixed.

**Comment by LinuxDonald** [comment]
Can you please upload the theme. That an dev can fix it.

**Comment by stubb** [comment]
Thats a task @Nightraven has to do.

**Comment by LinuxDonald** [comment]
https://drive.google.com/file/d/0B-E3BKmwAl-FMFJkUUJURzJFVUk/view?usp=sharing

**Comment by stubb** [comment]
I took some time to inspect the old and the new theme. phpbb2 vs 3. The theme and templates differ in many places. Instead of hack the old theme into the format of the new we should consider adopting our theme to phpBB3. If I understood it correctly our theme inherits from the default theme named "prosilver". But instead of inherit it correctly, its a simple copy of the theme which was modified afterwards. Is anybody up to do these changes?

**Comment by LinuxDonald** [comment]
I close this because we install an new forum. Because we dont have access to the old one.
