### ISSUE TITLE
Settler stages grafic´s dont show up ingame

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2388]
The settler stages grafic´s dont show up ingame. Only its shows the sailer grafics.

TIER.PIONEERS: and TIER.SETTLERS: dont show up.

stubb maybe you can find an fix that Jana can render all martins grafics and add them into the game :)

https://github.com/unknown-horizons/unknown-horizons/blob/master/content/objects/units/collectors/settlercollector.yaml

**Comment by LinuxDonald** [comment]
Janexx have tested it when you comment out TIER.PIONEERS: and TIER.SETTLERS: it loads the grafics as Sailors one but the are in other folders see: https://github.com/unknown-horizons/unknown-horizons/tree/master/content/gfx/units/inhabitant

I think it dont check for Tier and that is maybe the problem. That it is not implemented.

**Comment by MasterofJOKers** [comment]
@LinuxDonald You're right, it is not implemented for units to be updated with the tier. Should I implement this just for the inhabitants or for other units as well?

**Comment by LinuxDonald** [comment]
i think there must be an way that the game checks in the yaml file. If there are defined grafics for the tier when yes that it load it. But the game must check what tier the buildings have too and that one building get an higher tier and than only runs on streets the newer tier grafics of people.

**Comment by MasterofJOKers** [comment]
Well, I can tell you, how it is done for buildings: When a new level is reached, every building is informed about it and tryies to load a new random action_set into itself. This can also be done for the buildings' collectors, which inhabitants are - but since tents behave a little different in that they initiate the level change, there are two places to implement having different grafics for collectors of buildings.

**Comment by LinuxDonald** [comment]
Fixed with https://github.com/unknown-horizons/unknown-horizons/commit/510fe098a7d12fdfb2fa4dd3ca0457e683d649d4
