### ISSUE TITLE
Repair/remove bind_all, make_constants in util/python/decorators

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2634]
These are bytecode hacks to improve performance apparantly. Either remove them or port them to python3 as well. In my previous attempt of the port the code didn't work out of the box. Might be a minor fix though.

**Comment by AndyMender** [comment]
So I looked into the code and it seems that the very source of the problem in the `_make_constants` function was `newcode = map(ord, co.co_code)` in the Python2 version.  The translated Python3 code is `newcode = list(map(ord, str(co.co_code, 'latin-1')))`. The problem was that `.co_code` is ISO8859-1 encoded type bytes, but the default for Python3 is utf-8. I fixed it by explicitly using latin-1/ISO8859-1 encoding.

This is however just the first fix, more will follow later and a full commit in the evening today.

**Comment by squiddy** [comment]
Yes it just isn't worth the hassle right now. The game will work without them. And they've been a source of bugs as well.

**Comment by AndyMender** [comment]
I removed function definitions for `_make_constants`, `bind_all` and `make_constants` from decorators.py then. We can probably close this issue for now, methinks.

**Comment by squiddy** [comment]
Did you also remove all *uses* of `bind_all`?

**Comment by AndyMender** [comment]
No, I'm doing it right now.
