### ISSUE TITLE
Get unittests / game tests working

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2635]
Figure out a good way to mock fife. The previous port kinda worked with some really ugly hacks around the Dummy object - there gotta be a better way.

**Comment by AndyMender** [comment]
Some of the tests are already running, but others fail either when the `Dummy` object is compared to an `int` in `if` statements, or due to the way nose handles testing, causing `sys.stdout.fileno()` to not return 1. The latter can be handled, the former might need extra changes to the `Dummy` object.

**Comment by AndyMender** [comment]
@LinuxDonald @squiddy I transferred some of the fixes from the other python3 branch and added an extra method to the `Dummy` object, but the tests now timeout instead of failing. The recent build is here: https://travis-ci.org/unknown-horizons/unknown-horizons/builds/220836056

Alongside Travis CI, it would probably be good to run the tests until the very end locally to exclude issues with the Travis CI virtual machine itself and get more complete logs.

**Comment by LinuxDonald** [comment]
Travis have an max time for jobs. If an job is longer then this time it will get killed. We need pre-built fife and fifechan packages.

**Comment by AndyMender** [comment]
As far as I can tell, there is an official package in the Debian repositories called "python-fife" for Python2-compliant FIFE. If you don't mind, I can get the package from the deb-src repository and try to build it locally with the Debian deb tool suite, using Python3-compatible FIFE from the GIT repository as the base.

Unfortunately, I have no means of hosting it anywhere afterwards, unless we're interested in submitting the package to the Debian repositories via the Debian Games Team.

**Comment by squiddy** [comment]
It's working fine now.
