### ISSUE TITLE
Routeconfig gui item selection is broken

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2648]
Open Routeconfig gui. Select two islands and try to add ressources into the trade route.
Nothing will happen instand of that the clicked item is added to it.
I have added an savegame for faster testing.
[trade.sqlite.zip](https://github.com/unknown-horizons/unknown-horizons/files/931122/trade.sqlite.zip)

**Comment by AndyMender** [comment]
I'll have a look at it as soon as I can :).

**Comment by squiddy** [comment]
Pretty sure we have a GUI test for that.

**Comment by AndyMender** [comment]
@squiddy, might it be test 40 as visible in this traceback: https://pastebin.com/ePEfR58M ?

**Comment by squiddy** [comment]
@AndyMender It definitly sounds related. I might have a look at this later today.

**Comment by AndyMender** [comment]
We definitely need your input on this, since at least to me the matter is not exactly trivial. So far, I managed to narrow down the issue to the "resources" VBox widget in the "traderoute_resource_selection" VBox. Running UH with --gui-log shows that each resource is registered as "__unnamed__/__unnamed__" as this is the default name provided by the FIFE's pychan Widget class. Meaning, our code doesn't overwrite it with the proper name for each resource.

The resource selection box is generated by `generate_resource_selection_dialog` in horizons/gui/tutil.py. I think the attribute assignment on lines 200 and 201 is wrong (why `button.button.x` and not `button.x `like in the dummy code some lines above?), but there seems to be more to it.

**Comment by squiddy** [comment]
Does this mean all the GUI tests run locally for you?

I did a blame on those files, and the last change was 3-4 years ago. One is 07ebe38417730bdcdcab3f1b9540f1ebc0e49b0f, which added a test for that code. There is also a comment here https://github.com/unknown-horizons/unknown-horizons/commit/07ebe38417730bdcdcab3f1b9540f1ebc0e49b0f#diff-5636f7df2c76037f66f02a1b0d5ee8b9L193:

```python
if hasattr(button, "button"): # for imagefillstatusbuttons
  			button.button.capture( cb )
 			button.button.name = "resource_%d" % res_id
```

`ImageFillStatusButton` used to be implemented by us, probably as a wrapper (not a subclass!), which would explain `button.button` to modify the actual widget. I haven't looked into the code yet, but my guess is some recent change in FIFE broke this.

**Comment by LinuxDonald** [comment]
Maybe something with the merge of pychan. Helios changed very much in there.

**Comment by AndyMender** [comment]
@squiddy yes, the GUI tests run locally, though not via Xvfb, but Xorg. That's cumbersome, but at least works. Both me and @LinuxDonald had problems with Xvfb even locally. I'm running the GUI tests again to see whether test 40 now works.

**Comment by squiddy** [comment]
Also @ChrisOelmueller thought the theory about FIFE changing things sounds plausible. But I don't feel like digging in the history to check what happened with `ImageFillStatusButton`.

**Comment by AndyMender** [comment]
Test 40 still fails: https://pastebin.com/jH2L8XgN. Yet, the routeconfig menu now works properly except for the overlapping tooltips. That, however, should probably be addressed separately :).

**Comment by AndyMender** [comment]
This is more of a dirty hack then a fix so I'll try to find a cleaner solution in the following days :).
For now, the routeconfig menu works, but looks ugly, because some of the widgets are loaded twice.

**Comment by AndyMender** [comment]
The current fixes are a result of trial-and-error. Apparently, if a VBox is part of a ScrollArea and it is directly attached to a child of a `self._gui` container (itself being a VBox):
`self._gui.findChild(name="traderoute_resources").addChild(dlg)`
a part of the tooltip properties of the directly attached VBox is lost. Also, the following cannot be done:
`self._gui.findChild(name="traderoute_resources").findChild(name="resources_scrollarea").addChild(dlg)`
as then the "resources_scrollarea" ScrollArea widget actually holding the VBox has a value of `None` (it doesn't exist yet).

The Settings menu has a similar issue and will be fixed in a similar manner :).
