### ISSUE TITLE
2019.1 Release ToDos

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2700]
Fife 0.4.2 Release Date: XX.XX.2019
Fifechan 0.1.5 Release Date: XX.XX.2019
UH 2019.1 Release Date: XX.XX.2019

Issues Open for UH 2019.1:
https://github.com/unknown-horizons/unknown-horizons/milestone/29

Changelog must be updated.

**Comment by MarkusHackspacher** [comment]
Other Idea, let call UH2017 for all Version with python 2. If fix a fault in 2017.2 call it 2017.3.
And for the base with python 3 call it UH2018 and to make a release with the actual code base UH2018 beta 1.
It is because the linux distributions like Debian have a stable and a testing branch, in the moment is UH2017.1 in Debian testing, goes at 17. June in the stable branch for the next two years.
So go only bugfixs the 2017.x and the distributions have a stable version.
And to call UH2018 beta 1 to get a greater attention in the social media, so that it is also visible to the outside that it goes on. And attracts a larger number of users to which also write a bugreport

**Comment by LinuxDonald** [comment]
we dont have any bug fixes for 2017.2 Version. All changes are python3 based.

**Comment by MarkusHackspacher** [comment]
Ok, if one day a bugfix goes into 2017.2 than call it 2017.2.1.
But I mean use not 2017 for the python 3 code base. In my opinion it is better to call it 2018.x.

**Comment by MartinX3** [comment]
Could you make a Release now and put the open issues into the "next milestone" box?

**Comment by LinuxDonald** [comment]
@jmdejong i have cleanup the milestone. Maybe #2222 could be done for the next release?
And #2716 should be easy to fix too. Maybe we should setup an new UH Master Server for MP because i dont have access to the old server... New version would not work with the old Server code.

**Comment by Jeeppler** [comment]
@MarkusHackspacher the next Debian version will Debian 10 "Buster". If the release can be released before the Buster release it could end up in the next Debian version.

**Comment by LinuxDonald** [comment]
The next release will be only python3. Python 2 is no longer supported for uh.

**Comment by MarkusHackspacher** [comment]
@Jeeppler please look at the date.
Now is the python3 codebase already in Debian testing, it call unknown-horizons 2017.2git20180906. https://packages.debian.org/testing/source/unknown-horizons

And python2 codebase in Debian stable call unknown-horizons 2017.1, the release file from github 2017.2 are in python2, too.
https://packages.debian.org/stable/source/unknown-horizons

**Comment by LinuxDonald** [comment]
@MarkusHackspacher have you experience with creating Deb packages or with creating ppa?

**Comment by LinuxDonald** [comment]
Windows:
Fife/Fifechan/UH deps are now updated to last version
SDKs are updated.
One bug must be fixed with appveyor or cegui  must be disabled for Windows Version for the release: https://github.com/fifengine/fifengine/issues/1070
After this we should ready for release.
Linux:
Only https://github.com/unknown-horizons/unknown-horizons/issues/2716 needs to be fixed.

**Comment by Jeeppler** [comment]
@LinuxDonald can you reach out to the Debian community as a maintainer of UH and ask the maintainer of the UH Debian package to update the existing package the moment 2019.1 is released? I do not think it will be a huge issue to update an existing package to the latest release.

**Comment by Jeeppler** [comment]
@MarkusHackspacher thanks for pointing to the packages. 

@LinuxDonald The `unknown-horizons 2017.2git20180906` will probably end up in Debian 10 "Buster" unless the outstanding issues can be resolved for the UH 2019.1 Release in time of the Soft Freeze (2019-02-12): https://release.debian.org/buster/freeze_policy.html. I am not a Debian maintainer. 
I assume the UH code base did not change significantly from git20180906 to today, so it should not require huge Debian package changes and qualify for the "Soft Freeze" time frame.

Fedora 30 has a similar [time line](https://fedoraproject.org/wiki/Releases/30/Schedule). It will be officially released at the end of April or beginning of May. The beta freeze will be around the beginning of March.

Ubuntu 19.04 "Disco Dingo" has [release dates](https://www.omgubuntu.co.uk/2018/11/ubuntu-19-04-release-features) in between Debian 10 and Fedora 30. The [feature freeze](https://wiki.ubuntu.com/FeatureFreeze) is at the 21st of Februray. This is when the Ubuntu team stops accepting new packages. 
Keep in mind, Ubuntu imports packages from Debian. Meaning if there is a UH 2019.1 release package in Debian it will probably imported into Ubuntu.
Ubuntu beta should be released in the end of March and the final release date is April 18, 2019. 

I personally use Fedora, Debian and Linux Mint. I am only an occasional player. One of my favorite games is Unknown Horizons and I am following it for years. However, I do not like to install PPAs and I will install whatever UH version is in the package distribution of my operation system.

**Comment by shirishag75** [comment]
@Jeeppler and @LinuxDonald I actually echoed the same concerns in https://bugs.debian.org/918425 just a few moments ago. 

Could you also look at the rest of the dependencies if any of them have changed as shared in the depends part of the wishlist bug shared above. 

I also just saw the control file  to see the build-depends of the game at https://salsa.debian.org/games-team/unknown-horizons/blob/master/debian/control and didn't see anything which might need fixing. 

The only problem I see as far as things are concerned is that we have very small window of opportunity . Usually ftp-masters (the gatekeepers who are responsible for state of  packages in Debian unstable or/and testing) are ok with approving packages which have been in unstable, bugs fixed and then are moved to testing for wider testing before getting to release. Even though, even if Markus, the maintainer does do all the required things and it does move to testing, there is no guarantee that it will be released with Buster as we usually have a 2-3 months freeze where we try to find and fix as many bugs as possible (RC bugs or Release-critical bugs should be 0) before a release is made. 

You may not have to pass so stringinent a test because the game is in optional  priority rather than in main - 
```

$ aptitude show unknown-horizons | grep Priority
Priority: optional
```

**Comment by LinuxDonald** [comment]
For fixing bug there is no time at the moment and no dev is available for the engine. We have at the moment only an coder for UH not for the engine. Maybe with the new versions we will find some new members.

**Comment by MartinX3** [comment]
We fans wish you good luck, people. :)

**Comment by Jeeppler** [comment]
@LinuxDonald can you create a release based on all the changes from 2018? Just call it release 2018.1. In my opinion it is better to have a release out which people can play, instead of a release which is super, super stable. After all UH is a game, meaning it is for peoples entertainment.

One thing to keep in mind that Python2 is only supported for another 11 months [1][2]. So, if you already did the Python2 to Python3 conversion from the time 2017.1 was release, than please release a new version of the game based on the Python3 code.

[1]: End of support for python 2.7?     https://stackoverflow.com/a/23062904/5256728
[2]: Python 2.7 will retire in...     https://pythonclock.org/

**Comment by LinuxDonald** [comment]
Our new version should be stable enough. We don't have an old branch of the python2 version of the game.

**Comment by Jeeppler** [comment]
@LinuxDonald thanks for releasing 2019.1.

**Comment by LinuxDonald** [comment]
:) Closing this now because done.

**Comment by Jeeppler** [comment]
I just installed Unknown Horizons in [PureOS](https://www.pureos.net/). It comes by default with version 2019.1. 

PureOS is a free GNU/Linux distribution based on Debian.
