### ISSUE TITLE
Game not starting in Windows10 X64

### ISSUE THREAD

**Issue by RitoonL** [unknown-horizons/unknown-horizons#2890]
Hey, 

I told about the Issue on IRC ...

The game won't start on my config, i don't know if it's related to my installation or a general issue.

No log generated, here is the output after lauchnig the .bat 

Tested non Admin / Admin the game still not starting

https://pastebin.com/Uc4PGTy3

I hope you will find what is wrong ...

Thanx and keep up the work !!!

**Comment by baka0815** [comment]
````Traceback (most recent call last):
  File "C:\Unknown-Horizons\python\lib\site-packages\fife\fife.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Unknown-Horizons\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: Le module spécifié est introuvable.````

Google Translate says ``The specified module was not found``

**Comment by LinuxDonald** [comment]
That dont really helps because we dont see what dll cant loaded :(

**Comment by baka0815** [comment]
Looks like it's something with the FIFE engine
````
Traceback (most recent call last):
  File "run_uh.py", line 381, in <module>
    main()
  File "run_uh.py", line 109, in main
    import horizons.main
  File "C:\Unknown-Horizons\unknown-horizons\horizons\main.py", line 41, in <module>
    from fife import fife as fife_module
  File "C:\Unknown-Horizons\python\lib\site-packages\fife\fife.py", line 21, in <module>
    _fife = swig_import_helper()
  File "C:\Unknown-Horizons\python\lib\site-packages\fife\fife.py", line 20, in swig_import_helper
    return importlib.import_module('_fife')
  File "C:\Unknown-Horizons\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_fife'
````

**Comment by jmdejong** [comment]
Can confirm this; I tested on a windows PC now.
Since the error is the same as when zlib was missing, I suspect that this is the generic error for something wrong with fife.
My guess would be that there is another dependency that's missing.

We should find a way to make swig give more helpful error messages.

**Comment by Beliaar** [comment]
I checked _fife.pyd with dependencies and found out that zlib.dll is missing. There is a zlib1.dll, but that seems to be the incorrect version. Using the newest version of zlib works, though.

@LinuxDonald It seems to compile with a zlib version that is not packaged with the installer. Also zlib1.dll is not being used at all.

**Comment by Beliaar** [comment]
@LinuxDonald I just made a change in the fife repository that should fix this. You will need to repackage the release once the build is finished.

**Comment by Beliaar** [comment]
What exactly does it not fix? If i use the new installer the game starts normally for me.

**Comment by LinuxDonald** [comment]
the libfife zip dont have the zlib.dll still only zlib1.dll

**Comment by Beliaar** [comment]
Hmm, the UH installer does install the correct zlib.dll for me.

**Comment by LinuxDonald** [comment]
Yeah because i have created an fife zip with the dll

**Comment by yakotsar** [comment]
Unknown Horizons has crashed. 

We are very sorry for this and want to fix the underlying error.
In order to do this, we need the information from the logfile:
C:\Users\kotsa\Documents\My Games\unknown-horizons\log\unknown-horizons-2019-01-16_21-34-55.log
Please give it to us via IRC or our forum, for both see http://unknown-horizons.org .
rizons\\python\\lib\\site-packages']
PATHSEP: ";" SEP: "\"
LD_LIBRARY_PATH: <undefined>
PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\STMicroelectronics\STM32 ST-LINK Utility\ST-LINK Utility;D:\Unknown-Horizons\python\Lib\site-packages\fife;C:\Users\kotsa\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\kotsa\AppData\Local\Programs\Python\Python37-32\;C:\Users\kotsa\AppData\Local\Microsoft\WindowsApps;C:\Users\kotsa\AppData\Local\GitHubDesktop\bin;C:\Users\kotsa\AppData\Local\atom\bin
PYTHONPATH <undefined>
Python version: sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
Platform: Windows-10-10.0.17134-SP0
Using fife version 0.4.2, at least 0.4.2 required
Traceback (most recent call last):
  File "run_uh.py", line 381, in <module>
    main()
  File "run_uh.py", line 122, in main
    ret = horizons.main.start(options)
  File "D:\Unknown-Horizons\unknown-horizons\horizons\main.py", line 171, in start
    horizons.globals.fife.init()
  File "D:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 171, in init
    self.cursor_images = {k: self.imagemanager.load(v) for k, v in cursor_images.items()}
  File "D:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 171, in <dictcomp>
    self.cursor_images = {k: self.imagemanager.load(v) for k, v in cursor_images.items()}
fife.fife.SDLException: _[SDLException]_ , SDL reported something bad :: Fatal Error when loading image into a SDL_Surface: Failed loading libpng16-16.dll: Не найдена указанная процедура.

**Comment by jmdejong** [comment]
I just asked someone else to try it too on windows and there was also an error popup.
The text in the popup translates to `unable to find access procedure for inflateValidate in zlib1.dll` (the word 'inflateValidate' was in english)

**Comment by yakotsar** [comment]
I have the same popup but about fife\libpng16-16.dll

**Comment by jmdejong** [comment]
When I run from within wine on my own computer it works fine (both in a 32bit and a 64bit wineprefix).
@LinuxDonald and @Beliaar does it also run work for you? and is this on real windows or wine?

**Comment by yakotsar** [comment]
Should I set up some dependencies, fifeengine or smth, or installer must do it solo?

**Comment by Beliaar** [comment]
It works for me on a real Windows 10 (64). Just ran the installer and started the game.

**Comment by jmdejong** [comment]
FIFE is the game engine that unknown-horizons uses. See https://www.fifengine.net/ and https://github.com/fifengine/fifengine/
The installer installs FIFE along with unknown-horizons, together with the python interpreter.
To use the python interpreter that was supplied with the installer, do

    C:\Unknown-Horizons\unknown-horizons>..\python\python.exe run_uh.py --debug-log-only

or alternatively run `run_uh.bat` instead (it does the same)

If you want to use the python interpreter that you have then you should install FIFE manually.
For installation instructions see http://docs.fifengine.net/developer-manual/en/#_building_fifengine_on_windows

**Comment by jmdejong** [comment]
@Beliaar is your computer in english? I notice that all the crashes happen on computers that are not in english. It would be weird though

**Comment by yakotsar** [comment]
Oh yea, now I understood, ty @jmdejong )
I want to try open run_uh.bat with admin rights, but in that case, I got the message:
"run_uh.py" is not an internal or external command, an executable program or a batch file.

is it a clue?

**Comment by jmdejong** [comment]
Does the file `C:\Unknown-Horizons\python\python.exe` exist?
because that's needed for the bat file.

**Comment by yakotsar** [comment]
yes, python.exe exists

**Comment by yakotsar** [comment]
btw, this is python 3.
and on https://github.com/fifengine/python-tutorials noticed python 2.7

is it a clue?

**Comment by yakotsar** [comment]
[fife.log](https://github.com/unknown-horizons/unknown-horizons/files/2766351/fife.log)
I found fife.log there are couple more strings before fife destroyed, maybe it helps

**Comment by Beliaar** [comment]
@jmdejong My Windows is set to german, so nope.

And procedure not found, I think, points it to being the wrong version. Though it would be strange that we get different results for the same set of files.

**Comment by trailhunter** [comment]
Hi Folks,
same Issue here. 
Installed with Installer 2019.1.186-Setup-VC15-x86 as mentioned by LinuxDonald.

 
Following the Log:

 Unknown Horizons has crashed. 

We are very sorry for this and want to fix the underlying error.
In order to do this, we need the information from the logfile:
C:\Users\walla\Documents\My Games\unknown-horizons\log\unknown-horizons-2019-01-17_10-23-14.log
Please give it to us via IRC or our forum, for both see http://unknown-horizons.org .
Frank\\Apps\\Unknown-Horizons\\python\\lib', 'D:\\Benutzer\\Frank\\Apps\\Unknown-Horizons\\python', 'D:\\Benutzer\\Frank\\Apps\\Unknown-Horizons\\python\\lib\\site-packages']
PATHSEP: ";" SEP: "\"
LD_LIBRARY_PATH: <undefined>
PATH: C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;D:\Benutzer\Frank\Apps\Unknown-Horizons\python\Lib\site-packages\fife;C:\Users\walla\AppData\Local\Microsoft\WindowsApps;
PYTHONPATH <undefined>
Python version: sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
Platform: Windows-10-10.0.17763-SP0
Using fife version 0.4.2, at least 0.4.2 required
Traceback (most recent call last):
  File "run_uh.py", line 381, in <module>
    main()
  File "run_uh.py", line 122, in main
    ret = horizons.main.start(options)
  File "D:\Benutzer\Frank\Apps\Unknown-Horizons\unknown-horizons\horizons\main.py", line 171, in start
    horizons.globals.fife.init()
  File "D:\Benutzer\Frank\Apps\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 171, in init
    self.cursor_images = {k: self.imagemanager.load(v) for k, v in cursor_images.items()}
  File "D:\Benutzer\Frank\Apps\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 171, in <dictcomp>
    self.cursor_images = {k: self.imagemanager.load(v) for k, v in cursor_images.items()}
fife.fife.SDLException: _[SDLException]_ , SDL reported something bad :: Fatal Error when loading image into a SDL_Surface: Failed loading libpng16-16.dll: Die angegebene Prozedur wurde nicht gefunden.

All files seems to be present in the mentioned paths as shown above in the log file.


Running Windows 10-64bit Version 1809 (Build 17763.253), German Version.

Regards

**Comment by yakotsar** [comment]
See! I dont think that Frank - russian, so Its not about language intervention)

**Comment by LinuxDonald** [comment]
i will create tomorrow an new test version.

**Comment by artarik** [comment]
I have the same error:"..Failed loading libpng16-16.dll."

**Comment by Xearoxde** [comment]
Yeah, me too. LinuxDonald tried to fix it.

Windows 10 Pro x64 rev 1809

**Comment by LinuxDonald** [comment]
At the weekend i will create again new installer we have some changes on engine side.

**Comment by LinuxDonald** [comment]
I hope this version will fix all problems: https://ci.appveyor.com/api/buildjobs/y5kepr6qasmj7qs2/artifacts/Unknown-Horizons-2019.1.209-Setup-VC15-x86.exe

**Comment by jakoch** [comment]
Nope :)
- the Dlls should be fine now, but:
- Atlas Generation is deactivated, you can see this here: https://github.com/unknown-horizons/uh-installer/blob/master/appveyor.yml#L18
  - you will run into Issue #2829 `FileNotFoundError: [Errno 2] No such file or directory: 'content/atlas.sql'` 
  - the Atlas Generation fails, because PIL/Pillow can not be imported, https://github.com/unknown-horizons/unknown-horizons/blob/master/horizons/engine/generate_atlases.py#L44
  - PIL/Pillow are installed, `C:\python37\scripts\pip.exe install pyyaml polib pillow future`

**Comment by LinuxDonald** [comment]
Okay finaly fixed: https://ci.appveyor.com/api/buildjobs/svvo97871g81l6vt/artifacts/Unknown-Horizons-2019.1.211-Setup-VC15-x86.exe

**Comment by jakoch** [comment]
Yes! Works now.

**Comment by Xearoxde** [comment]
I can confirm it. It's now working. Thanks to God @LinuxDonald
