### ISSUE TITLE
Layers seem confused when selecting building, wrong z-order

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#661]
I only have seen this coincidentally now in one of my screenshots, but I guess there are more situations in which you can experience it.

Have a look at the picture, hope that it is self-explanatory.

---

`edit` 2011 Sep 09: New pic, new save, still existing:
*http://trac.unknown-horizons.org/t/raw-attachment/ticket/1015/z-order.png
*http://trac.unknown-horizons.org/t/raw-attachment/ticket/1015/z-order.sqlite

[> Link to originally reported Trac ticket <](http://trac.unknown-horizons.org/t/ticket/661)
**Attachment**: [2010-07-26.01-31-40.397362.png](http://up.unknown-horizons.org/f/?id=117&n=2010-07-26.01-31-40.397362.png)
**Attachment**: [eoc-layer.sqlite](http://up.unknown-horizons.org/f/?id=118&n=eoc-layer.sqlite)
##

**Comment by AndyMender** [comment]
Per the refactored up-to-date Python3-based code base, the problem still persists. Interestingly, the offender is exclusively the main square. Might the main square being treated as a road be the source of the problem?

**Comment by jmdejong** [comment]
This does not only happen to the main square, it happens to mines as well. I think the problem is a small building and a large building next to each other.

This seems to be a FIFE problem. The problem is with the x and y shift of an image. When an image has x and y shift (I believe that applies to all building images) the xy position of the sprite is updated, but the z position (which defines the ordering) isn't.

The problem is in LayerCache::updatePosition:
https://github.com/fifengine/fifengine/blob/bd53d8e3cfda733cd7989c7bf269a11e9a58edff/engine/core/view/layercache.cpp#L695
`screenPosition.x` and `screenPosition.y` are being corrected with the x and y shift of the image, but `screenPosition.z` isn't.

I have managed to fix it for me in https://github.com/jmdejong/fifengine/tree/zshifthack
https://github.com/jmdejong/fifengine/blob/d21a69168f93337e70e52434458eb4eeda5cd07d/engine/core/view/layercache.cpp#L705
I added a single line to set the correct z position. This line feels very hacky though, so if anyone know a better solution that would be great.

**Comment by AndyMender** [comment]
In principle, the need to apply any sort of shifts (X, Y or Z) to the object images should not exist to begin with. We have tons of extremely hackish code to handle images of different dimensions merely to counteract this problem.

Tracking the Z position of a building vs other buildings is obviously a different ball game. Should the most recent building overshadow the others as being the most recent addition to the layer?

**Comment by jmdejong** [comment]
This is indeed a problem in the shifts and not in FIFE.

Some shifts are always needed, because the location of the center of a tile/building on the image does not correspond to the center of the image. This is a known shift of `image.width/4-image.height/2` for all images.
We could change the sprites to make sure that these to match, but that would mean adding a lot of empty space below all sprites.

The z position ordering of buildings is determined by the y position. Buildings higher in the screen are "further away" from the camera and should be drawn behind buildings that are closer to the camera.
Fife does this automatically.
The problem is what to choose as the origin point for the x and y position. In the current situation this is a bit vague and undetermined. That is the source of the z-order problems. In pr #2804 I made the origin always the correspond to the center of the ground covered by the building (or tile or unit), which fixes this problem.

There is another problem that the ordering might be off for non-square buildings because it is possible for part of the building to be behind a building that is further away. This can only be solved by using multiple sprites for one building.

**Comment by jmdejong** [comment]
Fun fact: this problem even seems to exist in the screenshot on the homepage of the website: https://github.com/unknown-horizons/unknown-horizons.github.io/blob/source/assets/static/homepage-screenshot.png
